spring:
  application:
    name: flixmate-backend

  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:flixmate;DB_CLOSE_DELAY=-1;MODE=PostgreSQL}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:flixmate.notifications@gmail.com}
    password: ${MAIL_PASSWORD:mockpassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

flixmate:
  security:
    jwt:
      secret: ${JWT_SECRET:407F1D2F407F1D2F407F1D2F407F1D2F407F1D2F407F1D2F407F1D2F407F1D2F}
      expiration-ms: 86400000 # 24 Hours
  tmdb:
    api-key: ${TMDB_API_KEY:2f4038e83265214a0dcd6ec2eb3276f5}
    base-url: https://api.themoviedb.org/3
  gemini:
    api-key: ${GEMINI_API_KEY:mock-key}
    base-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent
  stripe:
    secret-key: ${STRIPE_SECRET_KEY:mock-key}
  omdb:
    api-key: ${OMDB_API_KEY:777d9323}
